---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: '0.2064'
  checked: true
- value: '0.2054'
  checked: false
- value: '0.2074'
  checked: false
- value: '0.2084'
  checked: false
name: New exercise
