---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: '0.7936'
  checked: true
- value: '0.7946'
  checked: false
- value: '0.7956'
  checked: false
- value: '0.7926'
  checked: false
name: New exercise
