---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: '0.0016'
  checked: true
- value: '0.0026'
  checked: false
- value: '0.0036'
  checked: false
- value: '0.0046'
  checked: false
name: New exercise
